import tempfile
from fpdf import FPDF

SKILL_LABELS = {
    "technical_knowledge": "Technical Knowledge",
    "communication": "Communication",
    "problem_solving": "Problem Solving",
    "confidence": "Confidence",
}

SKILL_WEIGHTS = {
    "technical_knowledge": "40%",
    "communication": "20%",
    "problem_solving": "30%",
    "confidence": "10%",
}

DECISION_COLORS = {
    "Strong Hire": (34, 197, 94),
    "Hire": (59, 130, 246),
    "Maybe": (245, 158, 11),
    "No Hire": (239, 68, 68),
}

# Brand colors
INDIGO = (79, 70, 229)
INDIGO_LIGHT = (99, 102, 241)
SLATE_900 = (15, 23, 42)
SLATE_500 = (100, 116, 139)
GREEN = (34, 197, 94)
AMBER = (245, 158, 11)
WHITE = (255, 255, 255)
GRAY_50 = (248, 250, 252)
GRAY_100 = (241, 245, 249)
GRAY_200 = (226, 232, 240)
GRAY_400 = (148, 163, 184)


def _safe(text: str) -> str:
    """Replace non-latin-1 chars so Helvetica doesn't choke."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


class ReportPDF(FPDF):
    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*GRAY_400)
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}}  |  Generated by Evaluet AI", align="C")


def generate_report_pdf(
    session_id: str,
    score: int,
    skill_scores: dict,
    strengths: list[str],
    improvements: list[str],
    hiring_decision: str,
    final_verdict: str,
    job_role: str,
    candidate_level: str,
    interviewer_name: str,
    created_at: str,
) -> str:
    pw = 210  # A4 width
    margin = 15
    content_w = pw - 2 * margin

    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ═══════════════════════════════════════════
    # HEADER BANNER — dark indigo
    # ═══════════════════════════════════════════
    pdf.set_fill_color(*INDIGO)
    pdf.rect(0, 0, pw, 52, style="F")

    pdf.set_xy(margin, 10)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*WHITE)
    pdf.cell(content_w, 12, "Interview Performance Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_x(margin)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(200, 200, 240)
    pdf.cell(content_w, 8, _safe(f"{job_role}  |  {candidate_level}"), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_x(margin)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(170, 170, 210)
    pdf.cell(content_w, 7, _safe(f"{interviewer_name}  |  {created_at}"), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)

    # ═══════════════════════════════════════════
    # SCORE + HIRING DECISION — centered cards
    # ═══════════════════════════════════════════
    card_w = 80
    card_x = (pw - card_w) / 2
    y_start = pdf.get_y()

    # Score box
    pdf.set_fill_color(*GRAY_50)
    pdf.rect(card_x, y_start, card_w, 36, style="F", round_corners=True, corner_radius=4)
    pdf.set_xy(card_x, y_start + 4)
    pdf.set_font("Helvetica", "B", 34)
    pdf.set_text_color(*INDIGO_LIGHT)
    pdf.cell(card_w, 18, f"{score}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(card_x, y_start + 22)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*GRAY_400)
    pdf.cell(card_w, 7, "OUT OF 100", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(y_start + 40)

    # Hiring decision badge
    r, g, b = DECISION_COLORS.get(hiring_decision, (100, 100, 100))
    badge_w = 60
    badge_x = (pw - badge_w) / 2
    badge_y = pdf.get_y()
    pdf.set_fill_color(r, g, b)
    pdf.rect(badge_x, badge_y, badge_w, 10, style="F", round_corners=True, corner_radius=3)
    pdf.set_xy(badge_x, badge_y + 1.5)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*WHITE)
    pdf.cell(badge_w, 7, _safe(hiring_decision), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(badge_y + 16)

    # ═══════════════════════════════════════════
    # SKILL BREAKDOWN
    # ═══════════════════════════════════════════
    _section_title(pdf, margin, "Skill Breakdown")

    row_h = 11
    for i, (key, label) in enumerate(SKILL_LABELS.items()):
        val = skill_scores.get(key, 0)
        weight = SKILL_WEIGHTS.get(key, "")
        y = pdf.get_y()

        # Alternating row bg
        if i % 2 == 0:
            pdf.set_fill_color(*GRAY_50)
            pdf.rect(margin, y, content_w, row_h, style="F")

        # Label + weight
        pdf.set_xy(margin + 4, y + 1)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*SLATE_900)
        pdf.cell(60, row_h - 2, _safe(label))

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*GRAY_400)
        pdf.cell(16, row_h - 2, weight)

        # Progress bar
        bar_x = margin + 84
        bar_y = y + 4
        bar_w = 75
        bar_h = 4
        pdf.set_fill_color(*GRAY_200)
        pdf.rect(bar_x, bar_y, bar_w, bar_h, style="F", round_corners=True, corner_radius=2)
        pdf.set_fill_color(*INDIGO_LIGHT)
        fill_w = max(bar_w * val / 100, 0.5)
        pdf.rect(bar_x, bar_y, fill_w, bar_h, style="F", round_corners=True, corner_radius=2)

        # Score value
        pdf.set_xy(bar_x + bar_w + 3, y + 1)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*INDIGO_LIGHT)
        pdf.cell(12, row_h - 2, str(val), align="R")

        pdf.set_y(y + row_h)

    pdf.ln(6)

    # ═══════════════════════════════════════════
    # STRENGTHS
    # ═══════════════════════════════════════════
    _card_section(pdf, margin, content_w, "Strengths", strengths, GREEN)

    # ═══════════════════════════════════════════
    # AREAS FOR IMPROVEMENT
    # ═══════════════════════════════════════════
    _card_section(pdf, margin, content_w, "Areas for Improvement", improvements, AMBER)

    # ═══════════════════════════════════════════
    # FINAL VERDICT
    # ═══════════════════════════════════════════
    if final_verdict:
        _section_title(pdf, margin, "Final Verdict")
        pdf.set_x(margin + 2)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(content_w - 4, 6, _safe(final_verdict))
        pdf.ln(6)

    # ── Save to temp file ──
    tmp = tempfile.NamedTemporaryFile(suffix=".pdf", prefix=f"report_{session_id[:8]}_", delete=False)
    pdf.output(tmp.name)
    return tmp.name


def _section_title(pdf: FPDF, margin: float, title: str):
    """Section heading with underline."""
    pdf.set_x(margin)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*SLATE_900)
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
    y = pdf.get_y()
    # Indigo accent line
    pdf.set_draw_color(*INDIGO_LIGHT)
    pdf.set_line_width(0.6)
    pdf.line(margin, y, margin + 40, y)
    # Light line rest
    pdf.set_draw_color(*GRAY_200)
    pdf.set_line_width(0.2)
    pdf.line(margin + 40, y, 210 - margin, y)
    pdf.ln(4)


def _card_section(pdf: FPDF, margin: float, content_w: float, title: str, items: list[str], accent_color: tuple):
    """A card with colored left border, title, and bullet items."""
    if not items:
        return

    # Pre-calculate height
    pdf.set_font("Helvetica", "", 10)
    line_h = 6
    title_h = 10
    padding = 6
    item_heights = []
    for item in items:
        # Estimate wrapped lines
        text = _safe(f"  {item}")
        lines = max(1, len(text) // 75 + 1)
        item_heights.append(lines * line_h + 2)
    total_h = title_h + sum(item_heights) + padding * 2

    # Check if we need a page break
    if pdf.get_y() + total_h > 280:
        pdf.add_page()

    y_start = pdf.get_y()

    # Card background
    pdf.set_fill_color(*GRAY_50)
    pdf.rect(margin, y_start, content_w, total_h, style="F", round_corners=True, corner_radius=4)

    # Left accent border
    r, g, b = accent_color
    pdf.set_fill_color(r, g, b)
    pdf.rect(margin, y_start + 2, 2.5, total_h - 4, style="F")

    # Title
    pdf.set_xy(margin + 8, y_start + padding)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(r, g, b)
    pdf.cell(content_w - 16, 8, title)
    pdf.set_y(y_start + padding + title_h)

    # Items
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    for item in items:
        pdf.set_x(margin + 10)
        pdf.cell(4, line_h, "-")
        pdf.multi_cell(content_w - 22, line_h, _safe(f" {item}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    pdf.set_y(y_start + total_h + 6)
