import os
from fpdf import FPDF

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports")

SKILL_LABELS = {
    "technical_knowledge": "Technical Knowledge",
    "communication": "Communication",
    "problem_solving": "Problem Solving",
    "confidence": "Confidence",
}

DECISION_COLORS = {
    "Strong Hire": (34, 197, 94),
    "Hire": (59, 130, 246),
    "Maybe": (245, 158, 11),
    "No Hire": (239, 68, 68),
}


class ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, "Evaluet AI - Interview Performance Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by Evaluet AI", align="C")


def _safe_text(text: str) -> str:
    """Strip characters that fpdf2 can't encode with latin-1."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_report_pdf(
    session_id: str,
    score: int,
    skill_scores: dict,
    strengths: list[str],
    improvements: list[str],
    hiring_decision: str,
    final_verdict: str,
    job_role: str,
    candidate_level: str,
    interviewer_name: str,
    created_at: str,
) -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)

    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ──
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 14, _safe_text(job_role), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, _safe_text(f"{candidate_level}  |  {interviewer_name}  |  {created_at}"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Overall Score ──
    pdf.set_fill_color(240, 243, 255)
    pdf.rect(60, pdf.get_y(), 90, 30, style="F")
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(99, 102, 241)
    y_score = pdf.get_y() + 2
    pdf.set_xy(60, y_score)
    pdf.cell(90, 16, f"{score} / 100", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_xy(60, y_score + 16)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(90, 10, "OVERALL SCORE", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # ── Skill Breakdown ──
    _section_heading(pdf, "Skill Breakdown")
    for key, label in SKILL_LABELS.items():
        val = skill_scores.get(key, 0)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(80, 8, _safe_text(label))
        # score bar background
        bar_x = pdf.get_x()
        bar_y = pdf.get_y() + 2
        bar_w = 80
        bar_h = 5
        pdf.set_fill_color(230, 230, 230)
        pdf.rect(bar_x, bar_y, bar_w, bar_h, style="F")
        # score bar fill
        pdf.set_fill_color(99, 102, 241)
        pdf.rect(bar_x, bar_y, bar_w * val / 100, bar_h, style="F")
        pdf.set_xy(bar_x + bar_w + 2, pdf.get_y())
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(15, 8, str(val), align="R", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Strengths ──
    _section_heading(pdf, "Strengths")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(30, 30, 30)
    for s in strengths:
        pdf.cell(6, 7, chr(8226))
        pdf.multi_cell(0, 7, _safe_text(f"  {s}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Areas for Improvement ──
    _section_heading(pdf, "Areas for Improvement")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(30, 30, 30)
    for s in improvements:
        pdf.cell(6, 7, chr(8226))
        pdf.multi_cell(0, 7, _safe_text(f"  {s}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Hiring Decision ──
    _section_heading(pdf, "Hiring Decision")
    r, g, b = DECISION_COLORS.get(hiring_decision, (100, 100, 100))
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(r, g, b)
    pdf.cell(0, 10, _safe_text(hiring_decision), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ── Final Verdict ──
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 7, _safe_text(final_verdict))
    pdf.ln(6)

    # ── Save ──
    path = os.path.join(REPORTS_DIR, f"report_{session_id}.pdf")
    pdf.output(path)
    return path


def _section_heading(pdf: FPDF, title: str):
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(220, 220, 220)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
